---
- name: Working with Playbooks
  hosts: ansible2.example.com
  tasks:
  - name: Install a package
    yum: 
      name: vsftpd
      state: present
  - name: Start & Enable vsftpd
    service:
      name: vsftpd
      state: started
      enabled: true
  - name: Create a readme file /var/ftp/pub/README
    copy:
      content: 'welcome to this FTP server'
      dest: /var/ftp/pub/README

    
    
   
