---
- name: Working with Playbooks
  hosts: ansible2.example.com
  tasks:
  - name: install vsftpd
    yum:
      name: vsftpd
      state: present
  - name: start & enable vsftpd
    service:
      name: vsftpd
      state: started
      enabled: true
  - name: create readme file 
    copy:
      content: 'welcome to this FTP server'
      dest: /var/ftp/pub/README
      mode: '0444'
      force: false
      
      
