---
- name: Create a user
  hosts: all
  vars_files:
  - secret.yaml
  tasks:
  - name: Create a user
    user:
      name: "{{ username }}"
      password: "{{ pwhash }}"
  - name: Verification
    shell: |
      id {{ username }}
      echo ''
      cat /etc/passwd | grep -i {{ username }}
    register: results
  - name: Print results
    debug:
      var: results
