---
- name: Variabled defined in Playbook (Play scope)
  hosts: all
  vars:
    username: lisa
  tasks:
  - name: Create user {{ username }} 
    user: 
      name: "{{ username }}"
      shell: /bin/bash
      state: present
