---
- name: using task control
  hosts: all
  ignore_errors: true
  tasks:
  - name: install & start database
    block:
    - name: install mariadb database service
      package: 
        name: 
        - mariadb-server
        - python3-PyMySQL
        state: absent
      when: (ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS') and ansible_distribution_major_version == '9'
    - name: start mariadb database service
      service:
        name: mariadb
        state: started
        enabled: true
      changed_when: true
      notify: 
      - set_root_password
      - test_root_login

  handlers:
  - name: set_root_password
    blockinfile:
      path: /root/.my.cnf
      block: |
        [client]
        user=root
        password=password
      create: true
  - name: test_root_login
    mysql_user:
      login_user: root
      login_password: password
      name: sally
      state: present
