---
- name: enable webserver
  hosts: ansible1.example.com
  tasks:
  - name: Install httpd & firewalld
    yum:
      name:
      - httpd
      - firewalld
      state: present
  - name: Install index.html
    copy:
      content: 'hello world'
      dest: /var/www/html/index.html
  - name: Start httpd
    service:
      name: httpd
      state: started
      enabled: yes
  - name: Start firewalld
    service:
      name: firewalld
      state: started
      enabled: yes
  - name: Open http Port
    firewalld:
      service: http
      permanent: yes
      state: enabled
      immediate: yes

- name: test webserver access
  hosts: localhost
  become: False
  tasks:
  - name: Connect to webserver
    uri:
      url: http://ansible1.example.com
      return_content: yes
    register: result
  - name: Print output
    debug:
      var: result.content
