---
- name: Using Ansible Vault - prompted for password
  hosts: all
  vars_files:
  - ./secret.yaml
  tasks:
  - name: create a user
    user:
      name: "{{ username }}"
      password: "{{ pwhash }}" 
      state: present
