collections:
- name: community.aws
- name: ansible.posix
- name: git+https://github.com/ansible-collections/community.general.git
  version: main
#- name: /tmp/my-collection.tar.gz
#- name: http://www.example.local/my-collection.tar.gz
