---
- name: Variables defined in playbook (play scope) 
  hosts: all
  vars_files:
  - vars/users.yaml
  tasks:
  - name: create a user
    user:
      name: "{{ username }}"
      shell: /bin/bash
      state: present
    
