---
- name: Variables defined in playbook (Play scope)
  hosts: all
  vars_prompt:
  - name: username
    prompt: What is your username?
    private: false
  tasks:
  - name: create a user
    user:
      name: "{{ username }}"
      state: present
 
