---
- name: Testing Multiple Conditions
  hosts: all
  tasks:
  - name: installs package httpd 
    package:
      name: httpd
      state: present
    when: ansible_distribution == "RedHat" and ansible_memfree_mb >= 1512
