---
- name: Dealing with failures
  hosts: all
  ignore_errors: true
  tasks:
  - name: create lv 'lvnothing'
    lvol:
      vg: vgnothing
      lv: lvnothing
      size: 1g
    register: output
  - name: print output of previous task
    debug: 
      var: output
  - name: print a message
    debug:
      msg: "volume group doesn't exist"
    failed_when: "'not found' in output.err"
