---
- name: Manage autoconnect
  hosts: ansible2.example.com
  vars:
    network_connections:
      # Create one ethernet profile and activate it.
      # The profile uses automatic IP addressing
      # and is tied to the interface by MAC address.
      - name: prod1
        state: up
        type: ethernet
        autoconnect: true
        mac: 00:0c:29:26:2e:a3
        mtu: 1450

  roles:
    - rhel-system-roles.network
