---
- name: multi-list
  hosts: ansible1.example.com
  vars_files:
    vars/users-list
  tasks:
  - name: Display messages
    debug:
      msg: User {{ item.username }} has homedirectory {{ item.homedir }} and shell {{ item.shell }}
    loop: "{{ users }}"
  - name: Print the second item
    debug:
      msg: the second item is {{ users[1] }}

