---
- name: multi-dictionary
  hosts: ansible1.example.com
  vars_files:
  - vars/users-dictionary
  tasks:
  - name: print user linda's stats
    debug:
      msg:
      - "User {{ users.linda.username }} has homedirectory {{ users.linda.homedir }} and shell {{ users.linda.shell }}"
