---
- name: multi-list
  hosts: ansible1.example.com
  vars_files:
  - vars/users-list
  tasks:
  - name: print user with their homedirectory and shell
    debug:
      msg:
      - "User {{ item.username }} has homedirectory {{ item.homedir }} and shell {{ item.shell }}"
    loop: "{{ users }}"
  - name: print the second item
    debug:
      msg:
      - "the second item is {{ users[1] }}"
